
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG


management:
  server:
    port: 8081

  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-details: always
    info:
      enabled: true

  health:
    livenessState: # 开启 /actuator/health/liveness
      enabled: true
    readinessState: # 开启 /actuator/health/readiness
      enabled: true

  metrics:
    enable:
      jvm: true
    use-global-registry: false
    tags:
      application: ${spring.application.name}

server:
  shutdown: graceful
  port: 8090

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  profiles:
    active: dev
  application:
    name: example-spring-security-jwe

  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: example-spring-security-jwt
          client-secret: example-spring-security-jwt-secret
          introspection-uri: http://localhost:8080/oauth2/introspect
