
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

server:
  shutdown: graceful
  port: 8090

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  profiles:
    active: dev
  application:
    name: example-spring-security-jwe

  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: example-spring-security-opaque
          client-secret: example-spring-security-opaque-secret
          introspection-uri: http://localhost:8080/oauth2/introspect
